// <auto-generated />
namespace SCIM_Processor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product_key_to_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_key_to_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201812200846598_product_key_to_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
