// <auto-generated />
namespace SCIM_Processor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product_code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_code));
        
        string IMigrationMetadata.Id
        {
            get { return "201811160947215_product_code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
