// <auto-generated />
namespace SCIM_Processor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productservice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productservice));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291235470_productservice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
